### ISSUE TITLE
Add "/" To Prefix in Makefile

### ISSUE THREAD

**Issue by nsstrickland** [solusipse/fiche#96]
It may be advisable to add a tailing `/` to the prefix in the Makefile (making it `/usr/local/bin/`), otherwise it will install fiche as a file at /usr/local/bin. If the `/` is added in, this should error out if the directory does not exist. 

```bash
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-che
cking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --ena
ble-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC)
```
----
```
sh$ stat /usr/local/bin
  File: /usr/local/bin
  Size: 36352           Blocks: 72         IO Block: 4096   regular file
Device: 800h/2048d      Inode: 256472      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:bin_t:s0
Access: 2019-06-09 16:35:07.017862677 +0000
Modify: 2019-06-09 16:35:07.017862677 +0000
Change: 2019-06-09 16:35:07.027862560 +0000
 Birth:
```
